/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmergencyContact {
  'relationship' : string,
  'name' : string,
  'phoneNumber' : string,
}
export interface EnergyLevel { 'date' : string, 'rating' : bigint }
export type EscalationPattern = { 'irritability' : null } |
  { 'overthinking' : null } |
  { 'shutdownFreeze' : null } |
  { 'racingMind' : null } |
  { 'emotionalEating' : null } |
  { 'sensoryOverload' : null } |
  { 'difficultySleeping' : null } |
  { 'procrastinationAvoidance' : null };
export interface FavoriteTool {
  'category' : ToolPreference,
  'toolName' : string,
}
export interface FocusReadiness { 'date' : string, 'rating' : bigint }
export type GoalFocus = { 'eatingRegulation' : null } |
  { 'productivity' : null } |
  { 'sleepRoutine' : null } |
  { 'emotionalSteadiness' : null } |
  { 'stressRegulation' : null } |
  { 'confidence' : null };
export interface HabitCompletion { 'habitName' : string, 'completed' : boolean }
export interface PersonalizedPlan {
  'weeklyReviewPrompt' : string,
  'dailyRoutines' : Array<string>,
  'resetSequence' : Array<ResetPlanStep>,
  'toolPreferences' : Array<ToolPreference>,
  'reminders' : Array<string>,
}
export interface RegulationRating {
  'afterReset' : bigint,
  'beforeReset' : bigint,
}
export interface ResetPlanStep {
  'microAction' : string,
  'coreQuestion' : string,
  'environmentAdjustment' : [] | [string],
  'name' : string,
  'regulationTool' : ToolPreference,
}
export interface SleepQuality { 'date' : string, 'rating' : bigint }
export type ToolPreference = { 'breath' : null } |
  { 'sensoryAnchors' : null } |
  { 'habitTracking' : null } |
  { 'audioGuidance' : null } |
  { 'journalingPrompts' : null };
export interface UserData {
  'sleepQuality' : Array<SleepQuality>,
  'personalizedPlan' : PersonalizedPlan,
  'focusReadiness' : Array<FocusReadiness>,
  'analyticsConsent' : boolean,
  'habitCompletions' : Array<HabitCompletion>,
  'textSize' : bigint,
  'emergencyContacts' : Array<EmergencyContact>,
  'regulationRatings' : Array<RegulationRating>,
  'energyLevels' : Array<EnergyLevel>,
  'highContrast' : boolean,
  'userProfile' : UserProfile,
  'favoriteTools' : Array<FavoriteTool>,
}
export interface UserProfile {
  'goalFocus' : GoalFocus,
  'resetPlan' : Array<ResetPlanStep>,
  'preferredTools' : Array<ToolPreference>,
  'escalationPatterns' : Array<EscalationPattern>,
}
export interface _SERVICE {
  'deleteUserData' : ActorMethod<[], undefined>,
  'getAllPersonalizedPlans' : ActorMethod<[], Array<PersonalizedPlan>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getEnergyLevels' : ActorMethod<[], Array<EnergyLevel>>,
  'getFocusReadiness' : ActorMethod<[], Array<FocusReadiness>>,
  'getHabitCompletions' : ActorMethod<[], Array<HabitCompletion>>,
  'getRegulationRatings' : ActorMethod<[], Array<RegulationRating>>,
  'getSleepQuality' : ActorMethod<[], Array<SleepQuality>>,
  'getUserData' : ActorMethod<[], [] | [UserData]>,
  'saveUserData' : ActorMethod<
    [
      UserProfile,
      PersonalizedPlan,
      Array<RegulationRating>,
      Array<SleepQuality>,
      Array<FocusReadiness>,
      Array<EnergyLevel>,
      Array<HabitCompletion>,
      Array<FavoriteTool>,
      Array<EmergencyContact>,
      bigint,
      boolean,
      boolean,
    ],
    undefined
  >,
  'updateEmergencyContacts' : ActorMethod<[Array<EmergencyContact>], undefined>,
  'updateFavoriteTools' : ActorMethod<[Array<FavoriteTool>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];