/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ToolPreference = IDL.Variant({
  'breath' : IDL.Null,
  'sensoryAnchors' : IDL.Null,
  'habitTracking' : IDL.Null,
  'audioGuidance' : IDL.Null,
  'journalingPrompts' : IDL.Null,
});
export const ResetPlanStep = IDL.Record({
  'microAction' : IDL.Text,
  'coreQuestion' : IDL.Text,
  'environmentAdjustment' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'regulationTool' : ToolPreference,
});
export const PersonalizedPlan = IDL.Record({
  'weeklyReviewPrompt' : IDL.Text,
  'dailyRoutines' : IDL.Vec(IDL.Text),
  'resetSequence' : IDL.Vec(ResetPlanStep),
  'toolPreferences' : IDL.Vec(ToolPreference),
  'reminders' : IDL.Vec(IDL.Text),
});
export const GoalFocus = IDL.Variant({
  'eatingRegulation' : IDL.Null,
  'productivity' : IDL.Null,
  'sleepRoutine' : IDL.Null,
  'emotionalSteadiness' : IDL.Null,
  'stressRegulation' : IDL.Null,
  'confidence' : IDL.Null,
});
export const EscalationPattern = IDL.Variant({
  'irritability' : IDL.Null,
  'overthinking' : IDL.Null,
  'shutdownFreeze' : IDL.Null,
  'racingMind' : IDL.Null,
  'emotionalEating' : IDL.Null,
  'sensoryOverload' : IDL.Null,
  'difficultySleeping' : IDL.Null,
  'procrastinationAvoidance' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'goalFocus' : GoalFocus,
  'resetPlan' : IDL.Vec(ResetPlanStep),
  'preferredTools' : IDL.Vec(ToolPreference),
  'escalationPatterns' : IDL.Vec(EscalationPattern),
});
export const EnergyLevel = IDL.Record({
  'date' : IDL.Text,
  'rating' : IDL.Nat,
});
export const FocusReadiness = IDL.Record({
  'date' : IDL.Text,
  'rating' : IDL.Nat,
});
export const HabitCompletion = IDL.Record({
  'habitName' : IDL.Text,
  'completed' : IDL.Bool,
});
export const RegulationRating = IDL.Record({
  'afterReset' : IDL.Nat,
  'beforeReset' : IDL.Nat,
});
export const SleepQuality = IDL.Record({
  'date' : IDL.Text,
  'rating' : IDL.Nat,
});
export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const FavoriteTool = IDL.Record({
  'category' : ToolPreference,
  'toolName' : IDL.Text,
});
export const UserData = IDL.Record({
  'sleepQuality' : IDL.Vec(SleepQuality),
  'personalizedPlan' : PersonalizedPlan,
  'focusReadiness' : IDL.Vec(FocusReadiness),
  'analyticsConsent' : IDL.Bool,
  'habitCompletions' : IDL.Vec(HabitCompletion),
  'textSize' : IDL.Nat,
  'emergencyContacts' : IDL.Vec(EmergencyContact),
  'regulationRatings' : IDL.Vec(RegulationRating),
  'energyLevels' : IDL.Vec(EnergyLevel),
  'highContrast' : IDL.Bool,
  'userProfile' : UserProfile,
  'favoriteTools' : IDL.Vec(FavoriteTool),
});

export const idlService = IDL.Service({
  'deleteUserData' : IDL.Func([], [], []),
  'getAllPersonalizedPlans' : IDL.Func(
      [],
      [IDL.Vec(PersonalizedPlan)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getEnergyLevels' : IDL.Func([], [IDL.Vec(EnergyLevel)], ['query']),
  'getFocusReadiness' : IDL.Func([], [IDL.Vec(FocusReadiness)], ['query']),
  'getHabitCompletions' : IDL.Func([], [IDL.Vec(HabitCompletion)], ['query']),
  'getRegulationRatings' : IDL.Func([], [IDL.Vec(RegulationRating)], ['query']),
  'getSleepQuality' : IDL.Func([], [IDL.Vec(SleepQuality)], ['query']),
  'getUserData' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
  'saveUserData' : IDL.Func(
      [
        UserProfile,
        PersonalizedPlan,
        IDL.Vec(RegulationRating),
        IDL.Vec(SleepQuality),
        IDL.Vec(FocusReadiness),
        IDL.Vec(EnergyLevel),
        IDL.Vec(HabitCompletion),
        IDL.Vec(FavoriteTool),
        IDL.Vec(EmergencyContact),
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateEmergencyContacts' : IDL.Func([IDL.Vec(EmergencyContact)], [], []),
  'updateFavoriteTools' : IDL.Func([IDL.Vec(FavoriteTool)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ToolPreference = IDL.Variant({
    'breath' : IDL.Null,
    'sensoryAnchors' : IDL.Null,
    'habitTracking' : IDL.Null,
    'audioGuidance' : IDL.Null,
    'journalingPrompts' : IDL.Null,
  });
  const ResetPlanStep = IDL.Record({
    'microAction' : IDL.Text,
    'coreQuestion' : IDL.Text,
    'environmentAdjustment' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'regulationTool' : ToolPreference,
  });
  const PersonalizedPlan = IDL.Record({
    'weeklyReviewPrompt' : IDL.Text,
    'dailyRoutines' : IDL.Vec(IDL.Text),
    'resetSequence' : IDL.Vec(ResetPlanStep),
    'toolPreferences' : IDL.Vec(ToolPreference),
    'reminders' : IDL.Vec(IDL.Text),
  });
  const GoalFocus = IDL.Variant({
    'eatingRegulation' : IDL.Null,
    'productivity' : IDL.Null,
    'sleepRoutine' : IDL.Null,
    'emotionalSteadiness' : IDL.Null,
    'stressRegulation' : IDL.Null,
    'confidence' : IDL.Null,
  });
  const EscalationPattern = IDL.Variant({
    'irritability' : IDL.Null,
    'overthinking' : IDL.Null,
    'shutdownFreeze' : IDL.Null,
    'racingMind' : IDL.Null,
    'emotionalEating' : IDL.Null,
    'sensoryOverload' : IDL.Null,
    'difficultySleeping' : IDL.Null,
    'procrastinationAvoidance' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'goalFocus' : GoalFocus,
    'resetPlan' : IDL.Vec(ResetPlanStep),
    'preferredTools' : IDL.Vec(ToolPreference),
    'escalationPatterns' : IDL.Vec(EscalationPattern),
  });
  const EnergyLevel = IDL.Record({ 'date' : IDL.Text, 'rating' : IDL.Nat });
  const FocusReadiness = IDL.Record({ 'date' : IDL.Text, 'rating' : IDL.Nat });
  const HabitCompletion = IDL.Record({
    'habitName' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const RegulationRating = IDL.Record({
    'afterReset' : IDL.Nat,
    'beforeReset' : IDL.Nat,
  });
  const SleepQuality = IDL.Record({ 'date' : IDL.Text, 'rating' : IDL.Nat });
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const FavoriteTool = IDL.Record({
    'category' : ToolPreference,
    'toolName' : IDL.Text,
  });
  const UserData = IDL.Record({
    'sleepQuality' : IDL.Vec(SleepQuality),
    'personalizedPlan' : PersonalizedPlan,
    'focusReadiness' : IDL.Vec(FocusReadiness),
    'analyticsConsent' : IDL.Bool,
    'habitCompletions' : IDL.Vec(HabitCompletion),
    'textSize' : IDL.Nat,
    'emergencyContacts' : IDL.Vec(EmergencyContact),
    'regulationRatings' : IDL.Vec(RegulationRating),
    'energyLevels' : IDL.Vec(EnergyLevel),
    'highContrast' : IDL.Bool,
    'userProfile' : UserProfile,
    'favoriteTools' : IDL.Vec(FavoriteTool),
  });
  
  return IDL.Service({
    'deleteUserData' : IDL.Func([], [], []),
    'getAllPersonalizedPlans' : IDL.Func(
        [],
        [IDL.Vec(PersonalizedPlan)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getEnergyLevels' : IDL.Func([], [IDL.Vec(EnergyLevel)], ['query']),
    'getFocusReadiness' : IDL.Func([], [IDL.Vec(FocusReadiness)], ['query']),
    'getHabitCompletions' : IDL.Func([], [IDL.Vec(HabitCompletion)], ['query']),
    'getRegulationRatings' : IDL.Func(
        [],
        [IDL.Vec(RegulationRating)],
        ['query'],
      ),
    'getSleepQuality' : IDL.Func([], [IDL.Vec(SleepQuality)], ['query']),
    'getUserData' : IDL.Func([], [IDL.Opt(UserData)], ['query']),
    'saveUserData' : IDL.Func(
        [
          UserProfile,
          PersonalizedPlan,
          IDL.Vec(RegulationRating),
          IDL.Vec(SleepQuality),
          IDL.Vec(FocusReadiness),
          IDL.Vec(EnergyLevel),
          IDL.Vec(HabitCompletion),
          IDL.Vec(FavoriteTool),
          IDL.Vec(EmergencyContact),
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateEmergencyContacts' : IDL.Func([IDL.Vec(EmergencyContact)], [], []),
    'updateFavoriteTools' : IDL.Func([IDL.Vec(FavoriteTool)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };