/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EnergyLevel {
    date: string;
    rating: bigint;
}
export interface EmergencyContact {
    relationship: string;
    name: string;
    phoneNumber: string;
}
export interface RegulationRating {
    afterReset: bigint;
    beforeReset: bigint;
}
export interface SleepQuality {
    date: string;
    rating: bigint;
}
export interface UserData {
    sleepQuality: Array<SleepQuality>;
    personalizedPlan: PersonalizedPlan;
    focusReadiness: Array<FocusReadiness>;
    analyticsConsent: boolean;
    habitCompletions: Array<HabitCompletion>;
    textSize: bigint;
    emergencyContacts: Array<EmergencyContact>;
    regulationRatings: Array<RegulationRating>;
    energyLevels: Array<EnergyLevel>;
    highContrast: boolean;
    userProfile: UserProfile;
    favoriteTools: Array<FavoriteTool>;
}
export interface FavoriteTool {
    category: ToolPreference;
    toolName: string;
}
export interface PersonalizedPlan {
    weeklyReviewPrompt: string;
    dailyRoutines: Array<string>;
    resetSequence: Array<ResetPlanStep>;
    toolPreferences: Array<ToolPreference>;
    reminders: Array<string>;
}
export interface HabitCompletion {
    habitName: string;
    completed: boolean;
}
export interface FocusReadiness {
    date: string;
    rating: bigint;
}
export interface ResetPlanStep {
    microAction: string;
    coreQuestion: string;
    environmentAdjustment?: string;
    name: string;
    regulationTool: ToolPreference;
}
export interface UserProfile {
    goalFocus: GoalFocus;
    resetPlan: Array<ResetPlanStep>;
    preferredTools: Array<ToolPreference>;
    escalationPatterns: Array<EscalationPattern>;
}
export enum EscalationPattern {
    irritability = "irritability",
    overthinking = "overthinking",
    shutdownFreeze = "shutdownFreeze",
    racingMind = "racingMind",
    emotionalEating = "emotionalEating",
    sensoryOverload = "sensoryOverload",
    difficultySleeping = "difficultySleeping",
    procrastinationAvoidance = "procrastinationAvoidance"
}
export enum GoalFocus {
    eatingRegulation = "eatingRegulation",
    productivity = "productivity",
    sleepRoutine = "sleepRoutine",
    emotionalSteadiness = "emotionalSteadiness",
    stressRegulation = "stressRegulation",
    confidence = "confidence"
}
export enum ToolPreference {
    breath = "breath",
    sensoryAnchors = "sensoryAnchors",
    habitTracking = "habitTracking",
    audioGuidance = "audioGuidance",
    journalingPrompts = "journalingPrompts"
}
export interface backendInterface {
    deleteUserData(): Promise<void>;
    getAllPersonalizedPlans(): Promise<Array<PersonalizedPlan>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getEnergyLevels(): Promise<Array<EnergyLevel>>;
    getFocusReadiness(): Promise<Array<FocusReadiness>>;
    getHabitCompletions(): Promise<Array<HabitCompletion>>;
    getRegulationRatings(): Promise<Array<RegulationRating>>;
    getSleepQuality(): Promise<Array<SleepQuality>>;
    getUserData(): Promise<UserData | null>;
    saveUserData(userProfileInput: UserProfile, personalizedPlanInput: PersonalizedPlan, regulationRatingsInput: Array<RegulationRating>, sleepQualityInput: Array<SleepQuality>, focusReadinessInput: Array<FocusReadiness>, energyLevelsInput: Array<EnergyLevel>, habitCompletionsInput: Array<HabitCompletion>, favoriteToolsInput: Array<FavoriteTool>, emergencyContactsInput: Array<EmergencyContact>, textSize: bigint, highContrast: boolean, analyticsConsent: boolean): Promise<void>;
    updateEmergencyContacts(emergencyContactsInput: Array<EmergencyContact>): Promise<void>;
    updateFavoriteTools(favoriteToolsInput: Array<FavoriteTool>): Promise<void>;
}
import type { EmergencyContact as _EmergencyContact, EnergyLevel as _EnergyLevel, EscalationPattern as _EscalationPattern, FavoriteTool as _FavoriteTool, FocusReadiness as _FocusReadiness, GoalFocus as _GoalFocus, HabitCompletion as _HabitCompletion, PersonalizedPlan as _PersonalizedPlan, RegulationRating as _RegulationRating, ResetPlanStep as _ResetPlanStep, SleepQuality as _SleepQuality, ToolPreference as _ToolPreference, UserData as _UserData, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserData();
            return result;
        }
    }
    async getAllPersonalizedPlans(): Promise<Array<PersonalizedPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPersonalizedPlans();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPersonalizedPlans();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnergyLevels(): Promise<Array<EnergyLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnergyLevels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnergyLevels();
            return result;
        }
    }
    async getFocusReadiness(): Promise<Array<FocusReadiness>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFocusReadiness();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFocusReadiness();
            return result;
        }
    }
    async getHabitCompletions(): Promise<Array<HabitCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabitCompletions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabitCompletions();
            return result;
        }
    }
    async getRegulationRatings(): Promise<Array<RegulationRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegulationRatings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegulationRatings();
            return result;
        }
    }
    async getSleepQuality(): Promise<Array<SleepQuality>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSleepQuality();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSleepQuality();
            return result;
        }
    }
    async getUserData(): Promise<UserData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserData();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserData();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveUserData(arg0: UserProfile, arg1: PersonalizedPlan, arg2: Array<RegulationRating>, arg3: Array<SleepQuality>, arg4: Array<FocusReadiness>, arg5: Array<EnergyLevel>, arg6: Array<HabitCompletion>, arg7: Array<FavoriteTool>, arg8: Array<EmergencyContact>, arg9: bigint, arg10: boolean, arg11: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserData(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0), to_candid_PersonalizedPlan_n38(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, to_candid_vec_n40(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserData(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0), to_candid_PersonalizedPlan_n38(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, to_candid_vec_n40(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async updateEmergencyContacts(arg0: Array<EmergencyContact>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmergencyContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmergencyContacts(arg0);
            return result;
        }
    }
    async updateFavoriteTools(arg0: Array<FavoriteTool>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFavoriteTools(to_candid_vec_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFavoriteTools(to_candid_vec_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_EscalationPattern_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscalationPattern): EscalationPattern {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FavoriteTool_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FavoriteTool): FavoriteTool {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GoalFocus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalFocus): GoalFocus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PersonalizedPlan_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonalizedPlan): PersonalizedPlan {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ResetPlanStep_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResetPlanStep): ResetPlanStep {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ToolPreference_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolPreference): ToolPreference {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserData_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserData): UserData {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserData]): UserData | null {
    return value.length === 0 ? null : from_candid_UserData_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalFocus: _GoalFocus;
    resetPlan: Array<_ResetPlanStep>;
    preferredTools: Array<_ToolPreference>;
    escalationPatterns: Array<_EscalationPattern>;
}): {
    goalFocus: GoalFocus;
    resetPlan: Array<ResetPlanStep>;
    preferredTools: Array<ToolPreference>;
    escalationPatterns: Array<EscalationPattern>;
} {
    return {
        goalFocus: from_candid_GoalFocus_n14(_uploadFile, _downloadFile, value.goalFocus),
        resetPlan: from_candid_vec_n4(_uploadFile, _downloadFile, value.resetPlan),
        preferredTools: from_candid_vec_n10(_uploadFile, _downloadFile, value.preferredTools),
        escalationPatterns: from_candid_vec_n16(_uploadFile, _downloadFile, value.escalationPatterns)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sleepQuality: Array<_SleepQuality>;
    personalizedPlan: _PersonalizedPlan;
    focusReadiness: Array<_FocusReadiness>;
    analyticsConsent: boolean;
    habitCompletions: Array<_HabitCompletion>;
    textSize: bigint;
    emergencyContacts: Array<_EmergencyContact>;
    regulationRatings: Array<_RegulationRating>;
    energyLevels: Array<_EnergyLevel>;
    highContrast: boolean;
    userProfile: _UserProfile;
    favoriteTools: Array<_FavoriteTool>;
}): {
    sleepQuality: Array<SleepQuality>;
    personalizedPlan: PersonalizedPlan;
    focusReadiness: Array<FocusReadiness>;
    analyticsConsent: boolean;
    habitCompletions: Array<HabitCompletion>;
    textSize: bigint;
    emergencyContacts: Array<EmergencyContact>;
    regulationRatings: Array<RegulationRating>;
    energyLevels: Array<EnergyLevel>;
    highContrast: boolean;
    userProfile: UserProfile;
    favoriteTools: Array<FavoriteTool>;
} {
    return {
        sleepQuality: value.sleepQuality,
        personalizedPlan: from_candid_PersonalizedPlan_n2(_uploadFile, _downloadFile, value.personalizedPlan),
        focusReadiness: value.focusReadiness,
        analyticsConsent: value.analyticsConsent,
        habitCompletions: value.habitCompletions,
        textSize: value.textSize,
        emergencyContacts: value.emergencyContacts,
        regulationRatings: value.regulationRatings,
        energyLevels: value.energyLevels,
        highContrast: value.highContrast,
        userProfile: from_candid_UserProfile_n12(_uploadFile, _downloadFile, value.userProfile),
        favoriteTools: from_candid_vec_n22(_uploadFile, _downloadFile, value.favoriteTools)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: _ToolPreference;
    toolName: string;
}): {
    category: ToolPreference;
    toolName: string;
} {
    return {
        category: from_candid_ToolPreference_n8(_uploadFile, _downloadFile, value.category),
        toolName: value.toolName
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weeklyReviewPrompt: string;
    dailyRoutines: Array<string>;
    resetSequence: Array<_ResetPlanStep>;
    toolPreferences: Array<_ToolPreference>;
    reminders: Array<string>;
}): {
    weeklyReviewPrompt: string;
    dailyRoutines: Array<string>;
    resetSequence: Array<ResetPlanStep>;
    toolPreferences: Array<ToolPreference>;
    reminders: Array<string>;
} {
    return {
        weeklyReviewPrompt: value.weeklyReviewPrompt,
        dailyRoutines: value.dailyRoutines,
        resetSequence: from_candid_vec_n4(_uploadFile, _downloadFile, value.resetSequence),
        toolPreferences: from_candid_vec_n10(_uploadFile, _downloadFile, value.toolPreferences),
        reminders: value.reminders
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    microAction: string;
    coreQuestion: string;
    environmentAdjustment: [] | [string];
    name: string;
    regulationTool: _ToolPreference;
}): {
    microAction: string;
    coreQuestion: string;
    environmentAdjustment?: string;
    name: string;
    regulationTool: ToolPreference;
} {
    return {
        microAction: value.microAction,
        coreQuestion: value.coreQuestion,
        environmentAdjustment: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.environmentAdjustment)),
        name: value.name,
        regulationTool: from_candid_ToolPreference_n8(_uploadFile, _downloadFile, value.regulationTool)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eatingRegulation: null;
} | {
    productivity: null;
} | {
    sleepRoutine: null;
} | {
    emotionalSteadiness: null;
} | {
    stressRegulation: null;
} | {
    confidence: null;
}): GoalFocus {
    return "eatingRegulation" in value ? GoalFocus.eatingRegulation : "productivity" in value ? GoalFocus.productivity : "sleepRoutine" in value ? GoalFocus.sleepRoutine : "emotionalSteadiness" in value ? GoalFocus.emotionalSteadiness : "stressRegulation" in value ? GoalFocus.stressRegulation : "confidence" in value ? GoalFocus.confidence : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    irritability: null;
} | {
    overthinking: null;
} | {
    shutdownFreeze: null;
} | {
    racingMind: null;
} | {
    emotionalEating: null;
} | {
    sensoryOverload: null;
} | {
    difficultySleeping: null;
} | {
    procrastinationAvoidance: null;
}): EscalationPattern {
    return "irritability" in value ? EscalationPattern.irritability : "overthinking" in value ? EscalationPattern.overthinking : "shutdownFreeze" in value ? EscalationPattern.shutdownFreeze : "racingMind" in value ? EscalationPattern.racingMind : "emotionalEating" in value ? EscalationPattern.emotionalEating : "sensoryOverload" in value ? EscalationPattern.sensoryOverload : "difficultySleeping" in value ? EscalationPattern.difficultySleeping : "procrastinationAvoidance" in value ? EscalationPattern.procrastinationAvoidance : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    breath: null;
} | {
    sensoryAnchors: null;
} | {
    habitTracking: null;
} | {
    audioGuidance: null;
} | {
    journalingPrompts: null;
}): ToolPreference {
    return "breath" in value ? ToolPreference.breath : "sensoryAnchors" in value ? ToolPreference.sensoryAnchors : "habitTracking" in value ? ToolPreference.habitTracking : "audioGuidance" in value ? ToolPreference.audioGuidance : "journalingPrompts" in value ? ToolPreference.journalingPrompts : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PersonalizedPlan>): Array<PersonalizedPlan> {
    return value.map((x)=>from_candid_PersonalizedPlan_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToolPreference>): Array<ToolPreference> {
    return value.map((x)=>from_candid_ToolPreference_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EscalationPattern>): Array<EscalationPattern> {
    return value.map((x)=>from_candid_EscalationPattern_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FavoriteTool>): Array<FavoriteTool> {
    return value.map((x)=>from_candid_FavoriteTool_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResetPlanStep>): Array<ResetPlanStep> {
    return value.map((x)=>from_candid_ResetPlanStep_n5(_uploadFile, _downloadFile, x));
}
function to_candid_EscalationPattern_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EscalationPattern): _EscalationPattern {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_FavoriteTool_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FavoriteTool): _FavoriteTool {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_GoalFocus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalFocus): _GoalFocus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PersonalizedPlan_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonalizedPlan): _PersonalizedPlan {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ResetPlanStep_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResetPlanStep): _ResetPlanStep {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_ToolPreference_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolPreference): _ToolPreference {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalFocus: GoalFocus;
    resetPlan: Array<ResetPlanStep>;
    preferredTools: Array<ToolPreference>;
    escalationPatterns: Array<EscalationPattern>;
}): {
    goalFocus: _GoalFocus;
    resetPlan: Array<_ResetPlanStep>;
    preferredTools: Array<_ToolPreference>;
    escalationPatterns: Array<_EscalationPattern>;
} {
    return {
        goalFocus: to_candid_GoalFocus_n27(_uploadFile, _downloadFile, value.goalFocus),
        resetPlan: to_candid_vec_n29(_uploadFile, _downloadFile, value.resetPlan),
        preferredTools: to_candid_vec_n34(_uploadFile, _downloadFile, value.preferredTools),
        escalationPatterns: to_candid_vec_n35(_uploadFile, _downloadFile, value.escalationPatterns)
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    microAction: string;
    coreQuestion: string;
    environmentAdjustment?: string;
    name: string;
    regulationTool: ToolPreference;
}): {
    microAction: string;
    coreQuestion: string;
    environmentAdjustment: [] | [string];
    name: string;
    regulationTool: _ToolPreference;
} {
    return {
        microAction: value.microAction,
        coreQuestion: value.coreQuestion,
        environmentAdjustment: value.environmentAdjustment ? candid_some(value.environmentAdjustment) : candid_none(),
        name: value.name,
        regulationTool: to_candid_ToolPreference_n32(_uploadFile, _downloadFile, value.regulationTool)
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weeklyReviewPrompt: string;
    dailyRoutines: Array<string>;
    resetSequence: Array<ResetPlanStep>;
    toolPreferences: Array<ToolPreference>;
    reminders: Array<string>;
}): {
    weeklyReviewPrompt: string;
    dailyRoutines: Array<string>;
    resetSequence: Array<_ResetPlanStep>;
    toolPreferences: Array<_ToolPreference>;
    reminders: Array<string>;
} {
    return {
        weeklyReviewPrompt: value.weeklyReviewPrompt,
        dailyRoutines: value.dailyRoutines,
        resetSequence: to_candid_vec_n29(_uploadFile, _downloadFile, value.resetSequence),
        toolPreferences: to_candid_vec_n34(_uploadFile, _downloadFile, value.toolPreferences),
        reminders: value.reminders
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: ToolPreference;
    toolName: string;
}): {
    category: _ToolPreference;
    toolName: string;
} {
    return {
        category: to_candid_ToolPreference_n32(_uploadFile, _downloadFile, value.category),
        toolName: value.toolName
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalFocus): {
    eatingRegulation: null;
} | {
    productivity: null;
} | {
    sleepRoutine: null;
} | {
    emotionalSteadiness: null;
} | {
    stressRegulation: null;
} | {
    confidence: null;
} {
    return value == GoalFocus.eatingRegulation ? {
        eatingRegulation: null
    } : value == GoalFocus.productivity ? {
        productivity: null
    } : value == GoalFocus.sleepRoutine ? {
        sleepRoutine: null
    } : value == GoalFocus.emotionalSteadiness ? {
        emotionalSteadiness: null
    } : value == GoalFocus.stressRegulation ? {
        stressRegulation: null
    } : value == GoalFocus.confidence ? {
        confidence: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolPreference): {
    breath: null;
} | {
    sensoryAnchors: null;
} | {
    habitTracking: null;
} | {
    audioGuidance: null;
} | {
    journalingPrompts: null;
} {
    return value == ToolPreference.breath ? {
        breath: null
    } : value == ToolPreference.sensoryAnchors ? {
        sensoryAnchors: null
    } : value == ToolPreference.habitTracking ? {
        habitTracking: null
    } : value == ToolPreference.audioGuidance ? {
        audioGuidance: null
    } : value == ToolPreference.journalingPrompts ? {
        journalingPrompts: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EscalationPattern): {
    irritability: null;
} | {
    overthinking: null;
} | {
    shutdownFreeze: null;
} | {
    racingMind: null;
} | {
    emotionalEating: null;
} | {
    sensoryOverload: null;
} | {
    difficultySleeping: null;
} | {
    procrastinationAvoidance: null;
} {
    return value == EscalationPattern.irritability ? {
        irritability: null
    } : value == EscalationPattern.overthinking ? {
        overthinking: null
    } : value == EscalationPattern.shutdownFreeze ? {
        shutdownFreeze: null
    } : value == EscalationPattern.racingMind ? {
        racingMind: null
    } : value == EscalationPattern.emotionalEating ? {
        emotionalEating: null
    } : value == EscalationPattern.sensoryOverload ? {
        sensoryOverload: null
    } : value == EscalationPattern.difficultySleeping ? {
        difficultySleeping: null
    } : value == EscalationPattern.procrastinationAvoidance ? {
        procrastinationAvoidance: null
    } : value;
}
function to_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ResetPlanStep>): Array<_ResetPlanStep> {
    return value.map((x)=>to_candid_ResetPlanStep_n30(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ToolPreference>): Array<_ToolPreference> {
    return value.map((x)=>to_candid_ToolPreference_n32(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<EscalationPattern>): Array<_EscalationPattern> {
    return value.map((x)=>to_candid_EscalationPattern_n36(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FavoriteTool>): Array<_FavoriteTool> {
    return value.map((x)=>to_candid_FavoriteTool_n41(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
